### ISSUE TITLE
python3 module build and runtime dependency issues

### ISSUE THREAD

**Issue by KarstenHopp** [modularity-modules/python3#3]
with the latest mbs changes, transient module dependencies get pulled in.
In python3 you have build requirements on bootstrap, python3-bootstrap and on perl. perl will now pull in the platform module. But platform conflicts with bootstrap and the build will fail.

As everything required for a python3 build, I'd suggest to leave the buildrequirement on bootstrap and drop the rest.

Also please note that platform-placeholder cannot be used in a module build. It was just a temporary workaround for the dependency resolution scripts. It will never be an official build or be available in PDC. Please drop that requirement.

**Comment by torsava** [comment]
> As everything required for a python3 build, I'd suggest to leave the buildrequirement on bootstrap and drop the rest.

I believe there are many python3 dependencies that are missing in platform but available in bootstrap. Last time I tried building with just platform, it looked like a lot of stuff would need to be modularized first.

> Also please note that platform-placeholder cannot be used in a module build. It was just a temporary workaround for the dependency resolution scripts. It will never be an official build or be available in PDC. Please drop that requirement.

Will do, thanks for the heads up!

**Comment by torsava** [comment]
Fixed.
