### ISSUE TITLE
Change the branch naming scheme

### ISSUE THREAD

**Issue by ncoghlan** [modularity-modules/python3#5]
The Py3 module currently only has a single stream name: `master`

This should be switched to be `3.6`, since we'd like the stream names to line up with "other modules that depend on this module must be rebuilt", and for CPython, that's the case when switching X.Y versions.

**Comment by torsava** [comment]
We have so far not decided to support multiple Python 3 stack in Fedora. So far we want to continue the established Fedora practice of supporting one Python 3 interpreter and stack. We do provide other Python interpreters (e.g. packages python35, python34, etc.), however without maintenance guarantees and without a package stack (thus they would have to be part of a different module). With that in mind, continuing on the `master` branch makes most sense to me at the moment.

Additionally, is there a precedent of module deprecating its master branch? All modules I've seen so far are using the `master` branch. With Modularity being not-yet-fully-baked at the moment, I don't know if we can even deprecate `master` and switch completely to a versioned branch.

**Comment by ncoghlan** [comment]
OK, here's the thing: the idea behind arbitrary branching is that we want to *get away from* the notion of creating a new branch of every package/module for each new Fedora release. Instead, we want downstream module branches to track upstream compatibility breaks that actually force rebuilds of their dependencies.

In the case of CPython, those forced rebuilds arise due to the changes to the filesystem layout, pyc file format, and the C ABI that accompany each new feature release. Accordingly, that means we have the following design goals:

* F27 and F28 should aim to share their modular Python 3 stacks (since they'll both be based on Python 3.6)
* F29 will switch to selecting the Python 3.7 branch as the default, but we'll still be building the 3.6 branch at that point for use in F27 and F28

The Python module dropping its default master branch will mean that the F27 System Profile will need to specify "the default Python branch is 3.6", but that's not only OK, it's the outcome we explicitly want.

There's a *separate* question, as to whether or not we allow the Python 3 stack to be switched away from the one that's the default specified in the System Profile (either forward 3.7, for F27 & F28 after work commences on F29, or backwards to 3.6 in F29).

The desired answer there is that switching will be possible, but it might block you from installing things that can't resolve their dependencies given that configuration. For right now though, we can hand wave the problem away a bit, since it won't actually come up in practice until the 3.7 branch for F29 gets created.

**Comment by ncoghlan** [comment]
To put the above another way:

* right now, Fedora has an "F25 Python 3 stack", an "F26 Python 3 stack", an "F27 Python 3 stack", and a "Rawhide Python 3 stack". Even if different Fedora versions share a major Python version, they still get a completely distinct Python stack.
* the goal is to get to a point where we can instead say that Fedora has a Python 3.6 stack (which is used in F27 and F28), and a Python 3.7 stack (which is used in F29, F30, etc)

Most Python applications will then be largely insulated from underlying Fedora platform changes, and can instead track the versions of the Python stack they support based on the test matrices of the relevant upstream projects.

**Comment by ignatenkobrain** [comment]
@ncoghlan probably very related question, what about renaming module to `python` which would have 2.7, 3.5, 3.6, ... streams instead of having python2 and python3 modules?

**Comment by ncoghlan** [comment]
Python 2 & 3 are parallel installable (and need to stay that way for backwards compatibility with Python 2 only applications), so they need to be separate modules

**Comment by torsava** [comment]
> @ncoghlan probably very related question, what about renaming module to python which would have 2.7, 3.5, 3.6, ... streams instead of having python2 and python3 modules?

@ignatenkobrain In addition to what Nick said, some Python programs/modules are just compatible with Python 2 or Python 3 but not both, which would make it even trickier.

**Comment by torsava** [comment]
@ncoghlan I agree, you're right. If we want to make the transition to F29 smoother, switching to a versioned branch in F27 would be advisable.

Can anyone point me to some most up-to-date resource to read up on service levels and ideally obsoleting branches (`master` specifically)?

And can this wait until after Modular Beta freeze, @whitel ? I'm leaving on PTO in a few hours, so I would have to find someone to delegate to otherwise.

**Comment by whitel** [comment]
@torsava currently we are using https://github.com/fedora-modularity/f27-content-tracking to track the names. I don't think we have a good doc yet about what to choose.

@nphilipp, @KarstenHopp thoughts?

**Comment by torsava** [comment]
Both `python3` and `python2` modules have now versioned branches (`3.6` and `2.7` respectively) while their `master` branches are left for development. The `pythonX-ecosystem` modules remain on master as they are to be built against all the respective streams of the Python modules.
