### ISSUE TITLE
RFE: Add python3-requests to python3-ecosystem

### ISSUE THREAD

**Issue by mhlavink** [modularity-modules/python3#6]
Please add python3-requests to python3-ecosystem module
This is quite basic python module and right now does not live anywhere. 
It is requested by cloud-init module, which can't satisfy this requirement atm.
Some other modules (pki, installer) bundle it, but it should be in this python3-ecosystem module, so they can drop this.

**Comment by torsava** [comment]
I'v submitted it as modular build #1093 (`mbs-build watch 1093`), but the builder has poor scheduling and it's stuck behind some hefty modules, so it's going to take a lot of time. Preliminary build on my local machine went well, so unless something else breaks it could be fine.

I'm away starting tomorrow for a week.

**Comment by ncoghlan** [comment]
This is in the module definition, but installing it in the boltron-f27 image doesn't currently work due to a missing runtime dependency:

```
$ docker run --rm -it jamesantill/boltron-27 bash -c 'dnf module enable python3-ecosystem && dnf install python3-requests'
Last metadata expiration check: 0:00:00 ago on Tue 17 Oct 2017 09:41:10 AM UTC.
'python3-ecosystem' is enabled
Last metadata expiration check: 0:00:05 ago on Tue 17 Oct 2017 09:41:10 AM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides python3-idna needed by python3-requests-2.18.4-1.module_416e449c.noarch
```

**Comment by mhlavink** [comment]
I've prepared bigger fix, that includes p-requests requirements, p-cryptography-vectors fix and some shuffled packages, that are unnecessarily bundled in pki, installer and cloud-init. Once I complete all tests, I will commit the fix.

**Comment by ncoghlan** [comment]
This has been committed here: https://src.fedoraproject.org/modules/python3-ecosystem/c/f2e33f6851aec5f5e22d4e00c6484d1a21b587f3?branch=master

**Comment by torsava** [comment]
Thanks, @mhlavink!
